Script fix

diff --git a/set-gdm-wallpaper b/set-gdm-wallpaper
--- a/set-gdm-wallpaper
+++ b/set-gdm-wallpaper
@@ -4,55 +4,65 @@
 
 set -e
 
+if ! hash gresource 2>/dev/null; then
+  echo "Library glib2-devel not found. dnf install -y glib2-devel"
+  exit 1
+fi
+
 if [ -n "$1" ]
 then
   workdir=$(mktemp -d)
   image="$1"
 else
   workdir="/usr/share/gnome-shell/wallpaper"
-  image="$workdir/gdm-image.png"
+  image="$workdir/wallpaper-gnome.png"
 fi
 
 if [ ! -f $image ]
 then
   echo "File not found: \"$image\" "
-  exit
+  exit 1
 fi
 
 echo "Updating wallpaper..."
 
-mkdir $workdir/theme
-
-gst=/usr/share/gnome-shell/gnome-shell-theme.gresource
-for r in `gresource list $gst`; do
-        gresource extract $gst $r >$workdir${r/#\/org\/gnome\/shell/}
-done
-
-cp $image $workdir/theme/image.jpg
+mkdir -p $workdir/theme
 
 echo '<?xml version="1.0" encoding="UTF-8"?>
 <gresources>
   <gresource prefix="/org/gnome/shell/theme">' > $workdir/gnome-shell-theme.gresource.xml
 
-ls $workdir/theme/ | sed 's/.*/    <file>&<\/file>/' >> $workdir/gnome-shell-theme.gresource.xml
+gst=/usr/share/gnome-shell/gnome-shell-theme.gresource
+for r in `gresource list $gst`; do
+  gfile="${r#\/org\/gnome\/shell\/theme/}";
+  mkdir -p "$(dirname $workdir/theme/$gfile)"
+
+  if [ "$gfile" != "wallpaper-gdm.png" ]; then
+    gresource extract $gst $r >$workdir/theme/$gfile
+    echo "    <file>$gfile</file>" >> $workdir/gnome-shell-theme.gresource.xml
+  fi
+done
+
+echo "    <file>wallpaper-gdm.png</file>" >> $workdir/gnome-shell-theme.gresource.xml
+cp -f $image $workdir/theme/wallpaper-gdm.png
 
 echo '  </gresource>
 </gresources>' >> $workdir/gnome-shell-theme.gresource.xml
 
-sed -i -e 's/background: #2e3436 url(resource:\/\/\/org\/gnome\/shell\/theme\/noise-texture.png);/background: #2e3436 url(resource:\/\/\/org\/gnome\/shell\/theme\/image.jpg);background-size: cover;/g' $workdir/theme/gnome-shell.css
+sed -i -e 's/background: #2e3436 url(resource:\/\/\/org\/gnome\/shell\/theme\/noise-texture.png);/background: #2e3436 url(resource:\/\/\/org\/gnome\/shell\/theme\/wallpaper-gdm.png);background-size: cover;/g' $workdir/theme/gnome-shell.css
 
-echo "// set-gdm-wallpaper" >> $workdir/theme/gnome-shell.css
-
-cd $workdir/theme/
+cd $workdir/theme
 glib-compile-resources $workdir/gnome-shell-theme.gresource.xml
 
-if ! grep -q "set-gdm-wallpaper" /usr/share/gnome-shell/gnome-shell-theme.gresource; then
-  cp /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.backup
+if ! grep -q "wallpaper-gdm.png" /usr/share/gnome-shell/gnome-shell-theme.gresource; then
+  cp -f /usr/share/gnome-shell/gnome-shell-theme.gresource /usr/share/gnome-shell/gnome-shell-theme.gresource.backup
+  echo "Backup"
 fi
 
+cp -f $workdir/gnome-shell-theme.gresource /usr/share/gnome-shell/
 
-cp $workdir/gnome-shell-theme.gresource /usr/share/gnome-shell/
-
-rm -rf $workdir/theme
+#rm -rf $workdir/theme
+#rm -f $workdir/gnome-shell-theme.gresource.xml
+#rm -f $workdir/gnome-shell-theme.gresource
 
 echo "Done!"
